# clippy allowed group
allow = ["cargo"]
# clippy warn group
warn = []
# clippy forbid group
forbid = [
    "complexity",
    "style",
    "nursery",
    "pedantic",
    "suspicious",
    "correctness",
    "perf",
]
# before cargo hooks
before-cargo = ["cargo fmt"]
# cargo hooks
cargo = [
    "verify-project",
    "check --all-targets --profile=test",
    "deny check",
    "audit",
    "test -j 4 --no-fail-fast -- --show-output",
    "fmt --check",
    "outdated",
]
# after cargo hooks
after-cargo = ["git status"]
