# Checks for usage of items through absolute paths, like std::env::current_dir.
[absolute_paths]
group = "restriction"
applicability = "unspecified"
# none < allow > warn deny
severity = "allow"
issue = "https://github.com/rust-lang/rust-clippy/issues?q=is%3Aissue+absolute_paths"
info = "https://rust-lang.github.io/rust-clippy/master/index.html#/absolute_paths"
# Checks for code like foo = bar.clone();
[assigning_clones]
group = "pedantic"
applicability = "unspecified"
# allow < warn > deny
severity = "warn"
issue = "https://github.com/rust-lang/rust-clippy/issues?q=is%3Aissue+assigning_clones"
info = "https://rust-lang.github.io/rust-clippy/master/index.html#/assigning_clones"
# 
Checks for if and match conditions that use blocks containing an expression, statements or conditions that use closures with blocks.
[blocks_in_conditions]
group = "style"
applicability = "machine-applicable"
# allow < warn > deny
severity = "warn"
issue = "https://github.com/rust-lang/rust-clippy/issues?q=is%3Aissue+blocks_in_conditions"
info = "https://rust-lang.github.io/rust-clippy/master/index.html#/blocks_in_conditions"
# Checks for attributes that allow lints without a reason.
[allow_attributes_without_reason]
group = "restriction"
applicability = "unspecified"
# allow < warn > deny
severity = "warn"
issue = "https://github.com/rust-lang/rust-clippy/issues?q=is%3Aissue+allow_attributes_without_reason"
info = "https://rust-lang.github.io/rust-clippy/master/index.html#/allow_attributes_without_reason"
# Checks for ranges which almost include the entire range of letters or digits.
[almost_complete_range]
group = "restriction"
applicability = "unspecified"
# allow < warn > deny
severity = "warn"
issue = "https://github.com/rust-lang/rust-clippy/issues?q=is%3Aissue+almost_complete_range"
info = "https://rust-lang.github.io/rust-clippy/master/index.html#/almost_complete_range"
# Checks for foo = bar; bar = foo sequences.
[almost_swaped]
group = "style"
applicability = "machine-applicable"
# allow warn < deny > none
severity = "deny"
issue = "https://github.com/rust-lang/rust-clippy/issues?q=is%3Aissue+almost_swaped"
info = "https://rust-lang.github.io/rust-clippy/master/index.html#/almost_swaped"
# 
Checks for floating point literals that approximate constants which are defined in std::f32::consts or std::f64::consts, respectively, suggesting to use the predefined constant.
[approx_constant]
group = "correctness"
applicability = "unspecified"
# allow warn < deny > none
severity = "deny"
issue = "https://github.com/rust-lang/rust-clippy/issues?q=is%3Aissue+approx_constant"
info = "https://rust-lang.github.io/rust-clippy/master/index.html#/approx_constant"
